version: '3.4'
services:
    npdservice: 
        build: 
            dockerfile: Dockerfile
            context: ./LicensePlateDetector
        ports:
          - "5002:5002"
    dbservie:
        build: 
            dockerfile: Dockerfile
            context: ./DataBase
        ports:
          - "5003:5003"
    