FROM python
 
COPY ./requirements.txt /Entrance/requirements.txt

WORKDIR /Entrance

RUN pip install -r requirements.txt

COPY . /Entrance

WORKDIR /app

ENTRYPOINT [ "python" ]

CMD [ "main.py" ]
