FROM python

MAINTAINER Dhanush 

COPY ./requirements.txt /NumberPlateDetector/requirements.txt

WORKDIR /NumberPlateDetector

RUN pip install -r requirements.txt

COPY . /NumberPlateDetector

WORKDIR app

ENTRYPOINT [ "python" ]

CMD [ "main.py" ]
