FROM python

MAINTAINER Dhanush 

COPY ./requirements.txt /SlotFinder/requirements.txt

WORKDIR /SlotFinder

RUN pip install -r requirements.txt

COPY . /SlotFinder

WORKDIR app

ENTRYPOINT [ "python" ]

CMD [ "main.py" ]
