FROM ubuntu:latest

RUN apt-get update -y

RUN apt-get install -y python-pip python-dev build-essential

WORKDIR /DataBase

COPY . /DataBase

RUN pip install -r requirements.txt

WORKDIR app

ENTRYPOINT [ "python" ]

CMD [ "database.py" ]

